### PR TITLE
add label with more specific origin info to ResOrigin in ResContainers

### PR DESCRIPTION
**Pull request by hendrikgit**

### CODE REVIEW

**Review by niv — COMMENTED** [review]
Not sure what the intent here is. Isn't the filename already part of the Res itself? The label in question here is meant to label the Origin.

**Comment by hendrikgit** [comment]
The filename is, but only the name not a path, if I remember correctly. I think I came across this with a tool I wrote where resources can be given via command line parameters and in an error message I wanted to show which file or container that res came from more specifically. Since more than one version of the same file could have been added (via command line in this case, maybe one was in a hak and one the file directly) and ResMan will return the last one added.

**Comment by niv** [comment]
Yea, ok!

**Comment by hendrikgit** [comment]
I think it is similar to what KeyTable does already https://github.com/niv/neverwinter.nim/blob/master/neverwinter/key.nim#L240.

**Pull request merged**
